version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7.22
    container_name: ${APP_NAME}_mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/${APP_NAME}-volume/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_USER: ${APP_NAME}
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  redis:
    image: redis:6.0.2-alpine
    container_name: ${APP_NAME}_redis
    ports:
      - "6379:6379"
    volumes:
      - /var/${APP_NAME}-volume/redis:/data
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    environment:
      SERVICE_NAME: ${APP_NAME}_web
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  composer:
    image: composer:1.8.3
    container_name: ${APP_NAME}_composer
    volumes:
      - ./:/app
      - /var/${APP_NAME}-volume/composer:/tmp
    working_dir: /app
    networks:
      - app-network

  npm:
    image: node:13.7
    container_name: ${APP_NAME}_npm
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: ['npm']
    networks:
      - app-network

  mailhog:
    container_name: ${APP_NAME}_mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
